import { readFile, writeFile } from 'node:fs/promises';
import { prepareCatalog } from '../server/seo/catalog.js';

// Each row describes an MFILM task. Different questions are exported explicitly,
// rather than counting accents, politeness wrappers or synthetic training samples.
const rows = `
Free trên MFILM có cần trả tiền thuê không?~Tại sao phim gói Free không có giá thuê?~Tôi thấy nhãn Free, có cần mua phim đó không?~Phim miễn phí có phải thanh toán thuê trước khi xem không?|Phim thuộc gói Free không cần trả giá thuê. Mở trang phim, chọn Xem Ngay và tập có nguồn phát. Nếu một phim đang ghi Free nhưng vẫn yêu cầu tiền thuê, gửi tên phim qua [Hỗ trợ](/ho-tro) để kiểm tra.
Gói MFILM được xếp từ thấp đến cao ra sao?~Basic hay Plus cao hơn trên MFILM?~Premium có cao hơn Plus không?~Sau gói Basic là gói nào của MFILM?|Thứ tự gói là **Free → Basic → Plus → Premium**. Premium là cấp cao nhất dành cho người xem. Xem giá và thời hạn đang áp dụng tại [Gói thành viên](/upgrade-vip).
Có cần mua Premium để xem tất cả phim Free không?~Tôi đang dùng Free thì xem phim Free ở đâu?~Muốn chỉ tìm phim không mất tiền trên MFILM phải làm gì?~Tôi không muốn thuê, làm sao chọn phim gói Free?|Bạn không cần mua Premium để xem phim thuộc gói Free. Khi chọn phim, kiểm tra nhãn Free trên thẻ hoặc trang chi tiết. Bạn cũng có thể hỏi chatbot gợi ý phim Free; danh sách cần được đối chiếu với kho phim đang tải.
Có thể thuê riêng phim dù chưa mua gói không?~Tôi chỉ muốn trả tiền cho một phim MFILM thì chọn gì?~Không muốn đăng ký cả gói, tôi có lựa chọn nào?~Muốn xem một phim trả phí một lần thì vào đâu?|Nếu trang phim có lựa chọn thuê hợp lệ, bạn có thể thuê riêng phim đó. Phim thuê được xem trong **30 ngày từ lúc thanh toán thành công**. Giá và quyền xem cần kiểm tra trên trang phim; thuê riêng không mở toàn bộ phim trong gói.
Thời gian thuê tính từ lúc xem hay lúc thanh toán?~Tôi trả tiền thuê nhưng chưa mở phim, hạn có bắt đầu chưa?~Thuê rồi để vài ngày mới xem có được tính lại 30 ngày không?~Hạn thuê MFILM bắt đầu vào thời điểm nào?|Thời hạn 30 ngày bắt đầu khi thanh toán thành công, không đợi lần xem đầu tiên. Kiểm tra ngày hết hạn trong Tài khoản → Phim Đang Thuê; chưa xem ngay không tự kéo dài thời hạn.
Thuê phim trên máy tính có xem trên điện thoại được không?~Đổi trình duyệt có mất quyền thuê MFILM không?~Tôi thuê ở Chrome rồi mở Edge có cần thuê lại không?~Phim thuê có đi theo tài khoản MFILM không?|Đăng nhập đúng tài khoản đã thuê trên thiết bị hoặc trình duyệt còn lại. Quyền thuê được kiểm tra theo tài khoản và thời hạn giao dịch; đăng nhập tài khoản khác không nhận quyền của tài khoản đã trả tiền.
Hết 30 ngày thuê có còn xem được không?~Phim đang thuê báo hết hạn thì xử lý thế nào?~Có tự cộng thêm 30 ngày khi mở lại phim thuê không?~Muốn tiếp tục xem sau khi hết hạn thuê phải làm gì?|Giao dịch thuê hết hạn không còn cấp quyền xem. Kiểm tra xem gói hiện tại có đủ quyền cho phim đó không; nếu chưa đủ, dùng lựa chọn thuê hoặc nâng cấp đang có trên trang phim. Việc mở lại phim không tự gia hạn.
Giá thuê phim của MFILM có giống nhau không?~Tại sao hai phim cùng web lại có giá thuê khác nhau?~Phim gói cao hơn có thể có giá thuê cao hơn không?~Có phải mọi phim đều thuê cùng một giá không?|Giá thuê gắn với từng phim và cấp gói, nên có thể khác nhau. Xem mức tiền đang hiển thị ở trang thanh toán của phim; phim Free không cần giá thuê. Chatbot không tự đặt mức tiền hoặc khẳng định giá từ dữ liệu cũ.
Tôi thanh toán nhầm tài khoản thì quyền xem nằm ở đâu?~Đã mua phim nhưng đang đăng nhập email khác thì sao?~Đổi tài khoản sau thanh toán có chuyển phim thuê không?~Không thấy phim đã thuê sau khi đổi email đăng nhập, cần kiểm tra gì?|Trước hết đăng nhập lại tài khoản đã thực hiện giao dịch và kiểm tra Phim Đang Thuê. Quyền xem không tự chuyển giữa tài khoản. Nếu cần kiểm tra giao dịch nhầm, liên hệ [Hỗ trợ](/ho-tro) với mã giao dịch, không gửi mật khẩu.
MFILM có thanh toán MoMo đang hoạt động chưa?~Có thể trả tiền bằng ZaloPay trên MFILM không?~Biểu tượng ShopeePay có nghĩa là đã thanh toán được chưa?~Nhấn VNPAY nhưng báo chưa hỗ trợ thì phải làm gì?|Chỉ sử dụng phương thức đang ghi được hỗ trợ trên trang thanh toán. Các biểu tượng ví hoặc thẻ có thể được giữ để trang trí dù phương thức chưa hoạt động. Nếu một phương thức ghi chưa hỗ trợ, chọn phương thức đang có; không chuyển tiền theo hướng dẫn lạ trong chat.
Tôi bấm PayPal nhưng chưa xác nhận, phim đã được thuê chưa?~Đóng cửa sổ PayPal trước khi trả tiền có mở phim không?~Nút thanh toán hiện ra đã có nghĩa giao dịch thành công chưa?~Tôi hủy ở bước thanh toán có được quyền xem phim không?|Mở trang thanh toán hoặc bấm PayPal chưa đồng nghĩa giao dịch thành công. Chỉ giao dịch được hệ thống xác nhận thành công mới cấp quyền thuê hoặc gói. Kiểm tra tài khoản và trạng thái giao dịch trước khi thử thanh toán lại.
Đã trừ tiền nhưng phim vẫn khóa thì báo gì cho MFILM?~Hỗ trợ cần thông tin nào khi tôi chưa nhận quyền xem?~Mua gói xong chưa cập nhật thì gửi bằng chứng gì?~Tôi không muốn gửi thông tin thẻ khi báo lỗi thanh toán thì sao?|Gửi mã giao dịch, tên phim hoặc gói, thời điểm thanh toán và trạng thái đang thấy qua [Hỗ trợ](/ho-tro). Có thể che thông tin nhạy cảm trên ảnh giao dịch. Không gửi số thẻ đầy đủ, mật khẩu hay mã xác thực trong chatbot.
Muốn xem giá gói đang áp dụng của MFILM vào đâu?~Chatbot có thể xác nhận giá Premium hôm nay từ trí nhớ không?~Giá cũ trong chat khác trang mua gói thì tin đâu?~Tôi cần bảng giá hiện tại của Free Basic Plus Premium ở đâu?|Mở [Gói thành viên](/upgrade-vip) để xem giá và thời hạn hiện tại. Thông tin thanh toán đang hiển thị là nơi cần đối chiếu trước khi mua; câu trả lời lưu sẵn không được dùng để khẳng định giá hôm nay.
Tôi cần tìm phim nhưng chỉ nhớ tên tiếng Anh thì sao?~Nhập tên gốc thay tên Việt trên MFILM có được không?~Phim có nhiều tên thì tôi nên tìm bằng tên nào?~Tên Việt không ra kết quả, tôi thử tên khác ở đâu?|Dùng ô tìm kiếm đầu trang với tên tiếng Việt hoặc tên khác của phim. Nếu có nhiều bản trùng tên, thêm năm hoặc phần phim; bạn có thể gửi tên nhớ được cho chatbot để tìm trong kho hiện tại.
Muốn mở danh sách phim mới MFILM vào đâu?~Phim vừa cập nhật nằm ở trang nào của MFILM?~Có trang riêng để tìm phim mới trên web không?~Tôi muốn duyệt kho phim mới thay vì hỏi chatbot, vào đâu?|Mở [Phim mới cập nhật](/film-new). Dùng phân trang để xem tiếp danh sách, rồi mở trang phim để kiểm tra tập và bản chiếu thực tế. Vừa cập nhật trên web không nhất thiết là vừa phát hành ngoài rạp.
Tìm phim bộ khác phim lẻ ở đâu trên MFILM?~Tôi muốn chọn phim một tập thay vì phim dài tập thì vào đâu?~Có mục riêng cho các phim nhiều tập không?~Muốn duyệt phim điện ảnh trên MFILM thì mở trang nào?|Dùng [Phim lẻ](/singleMovies) khi muốn duyệt phim điện ảnh và [Phim bộ](/series) khi muốn xem phim nhiều tập. Xem thông tin từng phim để xác nhận thời lượng và danh sách tập đang có.
Lọc phim theo quốc gia trên MFILM thế nào?~Muốn tìm riêng phim Hàn trên web thì bấm đâu?~Tôi cần phim Trung Quốc trong kho MFILM thì tìm thế nào?~Muốn duyệt phim Việt Nam thay vì toàn bộ phim thì làm sao?|Mở Quốc gia trên thanh điều hướng và chọn tên nước. Ở trang chi tiết phim, bạn cũng có thể bấm tên quốc gia để mở danh sách tương ứng. Danh mục là dữ liệu kho MFILM, không phải danh sách tất cả phim của nước đó.
Tìm phim theo thể loại trên MFILM thế nào?~Tôi muốn danh sách phim hành động của web thì bấm đâu?~Có thể bấm nhãn thể loại ở trang phim để tìm phim tương tự không?~Bộ lọc Thể loại trên đầu trang dùng ra sao?|Mở Thể loại, tìm tên thể loại rồi chọn để xem các phim phù hợp trong kho. Tên thể loại trên trang chi tiết cũng là liên kết tới danh sách đó; một phim có thể thuộc nhiều thể loại.
Tôi thích một diễn viên thì tìm phim của họ ở đâu?~Tên diễn viên trên MFILM có dẫn đến các phim đã tham gia không?~Muốn duyệt danh sách diễn viên trên web vào đâu?~Diễn viên có trang riêng trên MFILM không?|Mở [Diễn viên](/actors), tìm người bạn quan tâm và mở trang chi tiết để xem phim đã tham gia trong kho. Bạn cũng có thể chọn diễn viên trong tab Diễn viên của một trang phim. Không có phim trong kho không đồng nghĩa họ chưa từng đóng phim.
Chủ đề phim của MFILM nằm ở đâu?~Tôi muốn xem bộ sưu tập phim theo chủ đề thì chọn mục nào?~Có trang gom phim theo sở thích trên MFILM không?~Tìm một bộ sưu tập phim trên web thế nào?|Mở [Chủ đề](/topic), chọn bộ sưu tập rồi xem các phim bên trong. Các bộ sưu tập giúp duyệt kho theo sở thích; kiểm tra nhãn gói và trang phim trước khi xem.
Tôi chỉ muốn duyệt anime có sẵn trên MFILM thì vào đâu?~MFILM có trang danh sách phim hoạt hình riêng không?~Muốn tìm anime trên web thay vì phim người thật, chọn trang nào?~Có liên kết mở danh mục anime MFILM không?|Bạn có thể mở [Anime và phim hoạt hình](/anime). Chọn phim rồi xem mô tả, nhãn độ tuổi, phụ đề và danh sách tập đang có. Không mặc định mọi anime đều dành cho trẻ nhỏ hoặc đều có đủ mọi tập.
Muốn xem phần giới thiệu mà chưa phát phim thì mở đâu?~Tôi muốn đọc thông tin phim MFILM trước khi mua được không?~Trang chi tiết phim có gì để chọn phim phù hợp?~Có cần vào trình phát để xem mô tả phim không?|Mở trang chi tiết phim để đọc giới thiệu, tên khác, thể loại, quốc gia, diễn viên và thông tin tập. Bạn không cần phát video để đọc các thông tin công khai này; quyền phát phụ thuộc gói hoặc thuê còn hạn.
Số cuối của khoảng 1–126 có phải là 126 nút tập không?~Một nhóm tập ghi 1–126 mà chỉ có 120 mục là vì sao?~Tại sao khoảng tập có số lớn hơn lượng tập trong nhóm?~Nhóm tối đa 120 tập có nghĩa số nhãn cuối luôn là 120 không?|Một nhóm chứa tối đa 120 mục có nguồn, nhưng nhãn tập có thể nhảy số hoặc gộp tập. Khoảng 1–126 mô tả nhãn đầu và cuối của nhóm, không có nghĩa có 126 video. MFILM không tạo thêm video cho số tập nguồn chưa cung cấp.
Tôi cần đi thẳng tới tập ở nhóm cuối thì làm sao?~Bộ phim dài có cần bấm mũi tên từng nhóm để tới tập cuối không?~Muốn tìm tập 900 trên MFILM thì thao tác thế nào?~Có thể tìm khoảng tập bằng số trong bộ chọn không?|Mở bộ chọn Khoảng tập và nhập số tập cần tìm để chọn nhóm chứa nhãn đó. Sau đó bấm tập có nguồn trong nhóm. Nếu số tập không có hoặc thuộc video gộp, kiểm tra nhãn khoảng và báo tên phim, số tập qua Hỗ trợ.
Không thấy tập 40 nhưng có tập 41 trên MFILM thì làm sao?~Danh sách tập nhảy số có phải tự tạo tập thiếu không?~Tập thiếu trong kho có thể xem ở đâu để kiểm tra?~Muốn báo một bộ phim bị thiếu tập cần gửi gì?|Kiểm tra các nhãn tập gộp và bản chiếu khác trước. Nguồn có thể chưa có video riêng cho số đó. Gửi tên phim, số tập và bản chiếu qua [Hỗ trợ](/ho-tro); chatbot không tạo link tập chưa có nguồn.
Đổi server có đổi tên phim đang xem không?~Một nguồn phát hỏng có nên thử nguồn khác cùng tập không?~Server 1 không chạy nhưng Server 2 có thì dùng thế nào?~Tôi muốn giữ tập đang xem và đổi nguồn phát thì làm sao?|Chọn lại cùng tập ở server hoặc bản chiếu còn hoạt động. Server là nguồn phát, không phải một phim mới; khả năng giữ vị trí có thể khác theo trình phát. Ghi lại số tập và vị trí trước khi đổi nếu bạn cần quay lại chỗ đang xem.
Có Vietsub nhưng không thấy thuyết minh thì chọn ở đâu?~MFILM có tự làm bản lồng tiếng cho mọi phim không?~Không tìm được bản tiếng Việt đọc thoại của một phim thì sao?~Bản chiếu chỉ hiện Vietsub có xem thuyết minh được không?|Chỉ chọn được bản chiếu mà phim có nguồn thực tế. Mở mục Bản chiếu để kiểm tra Vietsub, thuyết minh hoặc lồng tiếng nếu có; không có lựa chọn đó thì không thể mặc định web tự tạo bản âm thanh mới.
Tôi vào đúng phim nhưng video là phim khác thì báo sao?~Tập phim trên MFILM phát sai nội dung, cần gửi thông tin gì?~Nguồn phát bị gắn nhầm tập thì xử lý thế nào?~Phát tập 5 mà nội dung giống tập 4 thì báo ở đâu?|Thử bản chiếu hoặc server khác của cùng tập để đối chiếu. Báo qua [Hỗ trợ](/ho-tro) với tên phim, số tập, server và thời điểm nhận ra sai nội dung. Không tự kết luận số tập phải đổi khi chưa kiểm tra nguồn.
Xem tiếp biến mất sau khi đăng nhập tài khoản khác thì sao?~Tại sao lịch sử phim ở hai tài khoản MFILM khác nhau?~Tôi đổi tài khoản rồi không thấy chỗ đã dừng thì kiểm tra gì?~Có dùng chung lịch sử xem giữa hai tài khoản MFILM không?|Lịch sử và tiến độ được tách theo tài khoản; lịch sử khách trên trình duyệt cũng có phạm vi riêng. Đăng nhập lại tài khoản đã xem và mở mục Xem Tiếp. Không dùng lịch sử của một người để trả lời thay cho người khác.
Mở hai máy cùng xem thì vị trí xem tiếp lấy của máy nào?~Tôi tua lùi trên máy tính rồi sang điện thoại, tiến độ có thể đổi không?~Muốn chuyển thiết bị mà không lưu nhầm tiến độ thì làm gì?~Hai thiết bị đang mở cùng phim thì nên dừng máy nào trước?|Dừng phát và chờ kết nối ở thiết bị đang xem trước khi chuyển. Tiến độ mới hơn được dùng khi đồng bộ, nên hai thiết bị cùng phát có thể gửi vị trí khác nhau. Kiểm tra đúng tập và vị trí ở thiết bị mới trước khi tiếp tục.
Mất mạng lúc xem phim có lưu được vị trí trên máy không?~Tạm thời offline có xóa hết tiến độ MFILM không?~Đóng trình duyệt khi mạng yếu có đồng bộ ngay không?~Tiến độ lưu cục bộ khác đồng bộ tài khoản thế nào?|Vị trí có thể lưu trên trình duyệt ngay cả khi tạm mất mạng. Đồng bộ giữa thiết bị cần đăng nhập và kết nối; hệ thống sẽ thử lại khi có mạng. Nếu xóa dữ liệu trình duyệt, dữ liệu chỉ lưu cục bộ có thể mất.
Muốn xóa một phim khỏi Xem Tiếp thì vào đâu?~Xóa lịch sử xem tiếp có xóa phim khỏi kho MFILM không?~Tôi không muốn một phim xuất hiện trong lịch sử nữa thì làm sao?~Xóa Xem Tiếp rồi xem lại phim có được lưu lại không?|Mở Tài khoản → Xem Tiếp và dùng thao tác xóa cho phim cần bỏ. Việc đó chỉ quản lý lịch sử của bạn, không xóa phim khỏi kho hoặc hủy thuê. Nếu sau đó xem lại phim, tiến độ mới có thể được lưu lại.
Yêu thích và Danh sách trên MFILM khác nhau thế nào?~Nút trái tim có tự thêm phim vào danh sách riêng không?~Tôi muốn chia phim theo nhiều danh sách thì chọn chức năng nào?~Lưu một phim để xem sau bằng Yêu thích hay Thêm vào?|Yêu Thích là danh sách phim đã bấm trái tim. Nút Thêm vào dùng để đưa phim vào danh sách bạn chọn. Cả hai giúp lưu phim để tìm lại nhưng không tự cấp quyền xem phim trả phí.
Thêm phim vào danh sách có làm mất quyền thuê không?~Xóa phim khỏi Yêu Thích có hủy tiền thuê không?~Tôi bỏ phim đã mua khỏi danh sách thì còn quyền xem không?~Danh sách phim có quyết định quyền thanh toán của tôi không?|Yêu thích và danh sách là cách tổ chức phim, tách với quyền thuê hoặc gói. Bỏ một phim khỏi danh sách không tự hủy giao dịch hay hoàn tiền. Kiểm tra quyền xem tại phim và Phim Đang Thuê.
Chia sẻ phim MFILM cho bạn bè nên gửi link nào?~Tôi muốn gửi trang phim mà không gửi link thanh toán thì sao?~Link có số tập có cần dùng để giới thiệu phim không?~Làm sao gửi liên kết phim rõ tên trên MFILM?|Mở trang chi tiết và dùng Chia sẻ hoặc sao chép đường dẫn dạng /phim/tên-phim. Người nhận có thể đọc thông tin công khai và tự chọn tập; quyền thuê hoặc gói của bạn không chuyển theo liên kết.
Xem trên điện thoại có cần cài ứng dụng ở hai nút store không?~Logo App Store của MFILM có bắt buộc tải app để xem không?~Tôi muốn dùng web MFILM trên iPhone mà không tải app thì sao?~Trên Android có mở MFILM trực tiếp bằng trình duyệt được không?|Bạn có thể dùng MFILM trực tiếp trong trình duyệt điện thoại. Để truy cập nhanh, xem [hướng dẫn thêm vào màn hình chính](/ho-tro#thiet-bi). Chỉ tải ứng dụng khi có liên kết phát hành chính thức hoạt động; biểu tượng cửa hàng không tự chứng minh app đã được phát hành.
Tại sao xoay điện thoại làm giao diện phim thay đổi?~Trang MFILM ở màn hình hẹp có cần dùng bản desktop không?~Khi thu nhỏ cửa sổ, tôi tìm chọn tập ở đâu?~Trên điện thoại các nút phim xuống hàng có bình thường không?|MFILM bố trí lại giao diện theo chiều rộng màn hình. Bạn vẫn dùng mục Tập phim, Khoảng tập và các nút server; không cần ép bản máy tính. Nếu số tập bị che hoặc nút không bấm được, gửi kích thước màn hình và ảnh qua Hỗ trợ.
Tôi thấy bản MFILM cũ sau khi bạn cập nhật thì làm sao?~Thông báo Có phiên bản mới trên MFILM nên bấm gì?~Trang web chưa nhận giao diện mới thì cập nhật thế nào?~Tôi có nên xóa tài khoản khi web chưa cập nhật không?|Nếu thấy thông báo Có phiên bản mới, bấm Cập nhật khi bạn đã sẵn sàng tải lại trang. Có thể thử tải lại trình duyệt. Không cần xóa tài khoản; trước khi tải lại hãy dừng video để lưu tiến độ.
Phim bị đen cả trang khác video đen thế nào?~Trang chủ MFILM trắng hoặc đen không có nút thì báo gì?~Không hiện giao diện web khác lỗi server phim ra sao?~Tôi không thấy cả tên phim và menu MFILM thì cần làm gì?|Nếu cả menu và nội dung không hiện, đó là lỗi tải trang khác với một server video hỏng. Thử tải lại và gửi đường dẫn, trình duyệt, thời điểm lỗi qua [Hỗ trợ](/ho-tro). Không cần thử đổi server khi giao diện chưa tải được.
Tôi xem phim có hình nhưng không nghe âm thanh thì sao?~Video MFILM tự tắt tiếng trên điện thoại phải làm gì?~Tăng loa máy mà phim vẫn im lặng thì kiểm tra đâu?~Server đang phát nhưng không có tiếng, tôi thử gì trước?|Bấm nút âm lượng trong trình phát và kiểm tra âm lượng của thiết bị hoặc tab. Trình duyệt có thể chặn phát âm thanh tự động nên cần thao tác phát trực tiếp. Nếu nguồn vẫn im lặng, thử server khác và báo tên phim, tập.
Không thấy phụ đề MFILM dù phim ghi Vietsub thì làm sao?~Chữ phụ đề bị mất trên một server thì xử lý gì?~Phụ đề bị lệch khi xem phim trên web nên báo sao?~Nguồn Vietsub không có chữ ở một tập thì thử gì?|Kiểm tra đúng bản Vietsub, thử server khác và mục phụ đề nếu trình phát có. Nếu phụ đề bị lệch hoặc thiếu, báo tên phim, tập, server và vị trí thời gian. Không mặc định trình phát nào cũng có điều chỉnh thời gian phụ đề.
Tôi muốn báo lỗi link phim MFILM không mở được thì gửi gì?~Link diễn viên báo không tìm thấy trên web cần làm sao?~Bạn gửi link phim sai trong chatbot thì tôi báo thế nào?~Liên kết tên phim cũ không tới trang mới thì cần kiểm tra gì?|Gửi đường dẫn lỗi và tên phim hoặc diễn viên bạn định mở qua [Hỗ trợ](/ho-tro). Thử tìm lại bằng ô tìm kiếm. Chatbot không nên tạo slug từ một tên chưa đối chiếu được với kho.
Chatbot có thể tự mở gói Premium cho tôi không?~Nhắn AI là đã thanh toán có tự mở khóa phim không?~Tôi yêu cầu chatbot cấp quyền xem thay vì trả tiền được không?~AI có tự thay đổi tài khoản thành VIP trên MFILM không?|Chatbot hướng dẫn và tìm phim, không tự cấp quyền Premium hoặc xác nhận thanh toán chỉ từ lời nhắn. Quyền xem phải được hệ thống đối chiếu gói và giao dịch hợp lệ của tài khoản.
Chatbot có nên đoán số tập mới hôm nay không?~Tôi hỏi lịch tập tuần tới thì AI có trả lời bằng trí nhớ được không?~Nguồn chưa cập nhật có thể để AI tự điền tập mới không?~Số tập hiện tại trong chat phải lấy từ đâu?|Số tập, lịch cập nhật và bản chiếu cần đối chiếu dữ liệu phim hiện tại. Nếu chưa có dữ liệu, chatbot nên nói chưa xác nhận thay vì tự bịa số, ngày hoặc link tập mới.
Tôi muốn gợi ý phim hợp gói của mình thì hỏi AI thế nào?~Làm sao để chatbot chỉ đề xuất phim tôi có quyền xem?~Tôi đang dùng Basic thì mô tả yêu cầu cho AI ra sao?~AI có cần biết gói khi gợi ý phim trên MFILM không?|Đăng nhập rồi nói rõ muốn phim hợp gói hiện tại, kèm thể loại hoặc quốc gia. Chatbot cần đối chiếu gói trong phiên và kho hiện tại; bộ hỏi đáp chung không dùng để khẳng định quyền cá nhân.
Tôi muốn phim nhẹ nhàng không kinh dị thì hỏi AI sao?~Chatbot MFILM cần thông tin nào để gợi ý đúng tâm trạng?~Tôi không muốn spoil khi xin gợi ý phim thì nói gì?~Muốn AI gợi ý phim ngắn dễ xem trên MFILM nên hỏi ra sao?|Nêu thể loại muốn xem, nội dung muốn tránh, độ dài, quốc gia và gói của bạn nếu cần. Ví dụ: gợi ý phim hài nhẹ nhàng trong kho MFILM, không kinh dị, không tiết lộ kết thúc. Danh sách phải lấy từ kho có thật.
Chatbot trả lời không liên quan tới MFILM thì báo gì?~AI hỏi phim lại nói kiến thức phổ thông thì tôi sửa thế nào?~Tôi muốn chatbot hiểu là đang hỏi web phim này thì nói sao?~Câu trả lời chatbot sai thao tác trên web thì gửi cho ai?|Nói rõ bạn đang hỏi thao tác nào trên MFILM và gửi lại câu hỏi nếu cần. Nếu đáp án vẫn sai, gửi câu hỏi cùng câu trả lời qua [Hỗ trợ](/ho-tro). Hướng dẫn web phải dựa trên tính năng thực tế; không dùng đáp án ngoài chủ đề để thay thế.
Tại sao chatbot không biết mật khẩu tài khoản của tôi?~Có nên nhập mã OTP vào chat MFILM để được hỗ trợ không?~AI có thể xem thông tin thẻ của người khác không?~Chatbot có chia sẻ tài khoản thuê phim cho người khác không?|Không gửi mật khẩu, OTP hoặc thông tin thẻ trong chat. Chatbot không tiết lộ thông tin riêng của người khác. Khi cần hỗ trợ tài khoản hoặc giao dịch, dùng kênh Hỗ trợ và thông tin xác minh phù hợp.
Link phim trả lời trong chat có bấm mở được không?~Tôi muốn AI gửi trang phim bằng tên thay vì ID thì hỏi sao?~Chatbot nên đưa link gì khi giới thiệu một phim MFILM?~AI có được tạo đường dẫn phim chưa có trong kho không?|Khi tìm được phim trong kho, chatbot dùng liên kết tới trang chi tiết theo tên. Nếu chưa tìm được tác phẩm tương ứng, cần hỏi thêm tên hoặc năm thay vì tự tạo một URL có vẻ đúng nhưng không mở được.
Tôi đổi tên hiển thị có ảnh hưởng phim thuê không?~Sửa ảnh đại diện có làm mất gói MFILM không?~Thông tin cá nhân nằm ở tab nào trong tài khoản?~Muốn chỉnh hồ sơ mà vẫn giữ lịch sử xem cần vào đâu?|Mở Tài khoản → Tài Khoản để chỉnh thông tin hoặc ảnh đại diện. Quyền thuê, gói và lịch sử theo tài khoản, không phải tên hiển thị. Đừng tạo một tài khoản khác chỉ để thay tên hoặc avatar.
Đăng nhập Google khác đăng nhập email trên MFILM thì chú ý gì?~Tôi có nhiều email Google thì chọn tài khoản nào để xem tiếp?~Muốn giữ đúng phim đã thuê khi đăng nhập lại phải làm sao?~Lần sau đăng nhập làm sao tránh vào nhầm tài khoản?|Dùng đúng phương thức và tài khoản đã xem hoặc thanh toán trước đó. Kiểm tra email trong hồ sơ sau khi đăng nhập. Nếu vào nhầm tài khoản, đăng xuất rồi chọn lại; lịch sử và quyền xem của hai tài khoản không tự gộp.
Trang lịch chiếu MFILM có bảo đảm ngày có tập online không?~Lịch chiếu rạp có giống lịch cập nhật phim trên web không?~Tôi thấy lịch chiếu nhưng chưa có video thì vì sao?~Có được suy ra giờ đăng tập từ lịch chiếu trên MFILM không?|[Lịch chiếu](/showtimes) và trạng thái video trong kho là hai thông tin khác nhau. Xem ngày, địa điểm và thông tin hiển thị ở lịch; mở trang phim để kiểm tra bản chiếu thực tế. Không tự suy ra thời điểm đăng tập online.
Phim có nhãn gói nhưng không có nút thuê hợp lệ thì sao?~Giá thuê trống có được coi là miễn phí không?~Một phim trả phí chưa hiển thị giá nên thanh toán thế nào?~AI thấy thiếu giá thuê có thể tự đặt giá giúp tôi không?|Phim Free không cần giá thuê, nhưng phim trả phí thiếu giá không được tự coi là miễn phí hoặc tự đoán tiền. Kiểm tra lại trang phim và [Hỗ trợ](/ho-tro) trước khi thanh toán; giá hợp lệ phải do hệ thống cung cấp.
Có nên trả tiền hai lần khi trang thanh toán bị đứng không?~PayPal đã báo thành công nhưng MFILM tải chậm thì bấm lại không?~Tôi không rõ giao dịch đã hoàn tất thì kiểm tra trước ở đâu?~Mạng mất sau khi thanh toán nên xử lý bước nào đầu tiên?|Kiểm tra tài khoản, Phim Đang Thuê hoặc gói và mã giao dịch trước khi trả tiền lại. Nếu nhà cung cấp báo đã thành công mà quyền chưa cập nhật, liên hệ Hỗ trợ để đối chiếu. Chatbot không xác nhận giao dịch chỉ dựa trên màn hình tải.
Muốn báo lỗi MFILM trên điện thoại cần ghi trình duyệt nào?~Tôi gửi ảnh lỗi resize web cần thêm thông tin gì?~Lỗi phim chỉ xảy ra trên Edge thì báo thế nào?~Báo lỗi giao diện MFILM cần những bước nào để tái hiện?|Gửi đường dẫn, thiết bị, trình duyệt, kích thước màn hình nếu liên quan, các bước thao tác và ảnh lỗi qua Hỗ trợ. Với video, thêm tên phim, tập và server. Những thông tin đó giúp phân biệt lỗi giao diện với lỗi nguồn phát.
Xóa lịch sử chat có xóa phim yêu thích không?~Tạo Chat mới có hủy phim thuê trên MFILM không?~Tôi đóng chatbot thì vị trí xem có bị xóa không?~Hội thoại AI và tài khoản phim có chung nút xóa không?|Chat mới hoặc xóa lịch sử hội thoại chỉ quản lý chat, không tự xóa phim yêu thích, quyền thuê hay tiến độ xem. Mỗi chức năng được quản lý ở khu vực riêng; đóng chatbot không hủy giao dịch.
Tôi hỏi phim vừa thêm mà AI chưa thấy thì làm gì?~Chatbot cần tải kho mới để tìm phim vừa nhập không?~AI không tìm thấy tên phim có trên web thì xử lý ra sao?~Phim mới thêm chưa có trong câu trả lời sẵn thì có nên bịa không?|Thử tải lại trang để nhận dữ liệu mới và gửi tên phim kèm phần hoặc năm. Chatbot ưu tiên đối chiếu kho hiện tại, không kết luận phim không tồn tại chỉ vì chưa có trong hỏi đáp sẵn; nếu chưa xác nhận được thì cần nói rõ.
Phim có giới hạn tuổi thì tôi kiểm tra ở đâu trên MFILM?~Hoạt hình trong kho MFILM có phải đều dành cho trẻ em không?~Tôi muốn chọn phim cho gia đình thì đọc thông tin nào trước?~Nhãn T13 T16 T18 trên thẻ phim dùng để chọn phim ra sao?|Đọc nhãn độ tuổi và giới thiệu trên thẻ hoặc trang chi tiết trước khi chọn phim. Hoạt hình cũng có thể chứa nội dung dành cho người lớn. Nếu thiếu phân loại đáng tin cậy, không nên mặc định phim phù hợp mọi độ tuổi.
Xem một tập nhiều lần có phải trả tiền thuê lại mỗi lần không?~Thuê còn hạn thì có mở lại cùng phim được không?~Tôi dừng giữa chừng rồi xem lại có mất ngày thuê còn lại không?~Trong 30 ngày thuê có phải mua riêng từng lần mở phim không?|Quyền thuê đang còn hạn áp dụng cho phim đã thuê; mở lại không tự tạo giao dịch mới hay đặt lại 30 ngày. Kiểm tra đúng tài khoản và ngày hết hạn trong Phim Đang Thuê. Từng nguồn vẫn cần có video hoạt động.
Chuyển từ máy tính sang điện thoại có phải tạo tài khoản MFILM mới không?~Tôi muốn dùng cùng danh sách phim trên hai thiết bị thì sao?~Muốn giữ Yêu Thích khi đổi máy phải làm gì?~Có nên đăng ký email mới mỗi lần mở MFILM trên thiết bị khác không?|Đăng nhập cùng tài khoản để giữ danh sách và quyền xem theo tài khoản. Xem tiếp cần kết nối để đồng bộ tiến độ. Không cần tạo tài khoản mới cho từng thiết bị.
Tôi muốn hỏi hỗ trợ mà không dùng AI thì liên hệ MFILM ở đâu?~Có kênh Zalo công khai của MFILM không?~Chatbot không xử lý được lỗi của tôi thì liên hệ ai?~Trang trợ giúp MFILM có nút liên hệ trực tiếp không?|Mở [Hỗ trợ MFILM](/ho-tro) và bấm Liên hệ MFILM để tới Zalo chính thức đang được web công khai. Gửi vấn đề cụ thể; không cần gửi mật khẩu hay thông tin thẻ để mô tả lỗi.
Một phim cùng tên có nhiều phần thì chọn đúng thế nào?~Tìm MFILM ra hai phim trùng tên, tôi so sánh gì?~Chatbot nên hỏi thêm gì nếu tôi chỉ nhớ tên series?~Tôi muốn tránh mở nhầm bản remake trên MFILM thì làm sao?|Đối chiếu tên khác, phần, năm phát hành, poster và giới thiệu trong từng trang phim. Khi hỏi chatbot, thêm các chi tiết bạn nhớ. Không nên chọn ngẫu nhiên một phim chỉ vì giống vài từ trong tên.
Trang phim ghi Vietsub có bảo đảm mọi server đều có phụ đề không?~Tôi cần xác nhận phụ đề của từng tập thì kiểm tra thế nào?~Nhãn thuyết minh trên phim có áp dụng mọi bản chiếu không?~Tập tôi mở không giống nhãn chung của phim thì làm gì?|Nhãn phim mô tả các định dạng có trong kho, còn nguồn của từng bản chiếu hoặc tập có thể khác. Kiểm tra đúng bản đang chọn và thử nguồn khác; báo lại tập bị sai nhãn để MFILM đối chiếu.
Tôi không thấy nút chất lượng 4K thì MFILM có tự nâng video không?~Chọn gói Premium có biến mọi phim thành 4K không?~Phim gói cao có bảo đảm mọi nguồn đều Full HD không?~AI có được khẳng định chất lượng phim từ tên gói không?|Gói quyết định quyền xem, không tự nâng độ phân giải của nguồn video. Chất lượng phụ thuộc bản phim và trình phát có lựa chọn tương ứng hay không; kiểm tra nguồn hiện tại, không suy ra 4K chỉ từ nhãn Premium.
Một liên kết phim thuê có giúp bạn tôi xem miễn phí không?~Tôi gửi link đang xem thì quyền gói có đi theo link không?~Chia sẻ phim trong thời hạn thuê có chia sẻ tài khoản không?~Bạn tôi mở link của tôi vẫn bị khóa có phải lỗi không?|Liên kết chỉ dẫn tới nội dung; quyền xem được kiểm tra theo tài khoản người nhận. Phim trả phí vẫn cần gói đủ quyền hoặc thuê còn hạn của tài khoản đó. Không gửi mật khẩu để chia sẻ quyền qua chat.
Xem Tiếp chỉ hiện một tập cũ thì tôi tìm tập mới ở đâu?~Muốn xem tập mới thay vì vị trí đã lưu trên MFILM phải làm gì?~Lịch sử xem có phải danh sách tất cả tập của phim không?~Tôi muốn chuyển tập khác sau khi mở Xem Tiếp thì chọn đâu?|Xem Tiếp đưa bạn về tiến độ đã lưu. Muốn chọn tập khác, mở Tập phim và bộ chọn Khoảng tập trên trang phim hoặc trình phát. Danh sách nguồn hiện tại quyết định tập nào có thể mở; lịch sử không tạo thêm tập.
Tôi vào web MFILM nhưng chatbot đưa tên phim không có link thì sao?~AI chỉ nói một tên phim có bảo đảm phim nằm trong kho không?~Tôi muốn gợi ý chỉ từ kho MFILM phải yêu cầu thế nào?~Không mở được phim do AI gợi ý thì nên hỏi lại gì?|Nói rõ muốn phim có trong kho MFILM và yêu cầu liên kết trang phim. Nếu chưa đối chiếu được, chatbot cần nói đó là gợi ý chưa xác nhận hoặc hỏi thêm, không coi mọi tên do mô hình nêu là phim có sẵn trên web.
Muốn theo dõi gói của tài khoản MFILM vào mục nào?~Tôi xem ngày hết hạn thành viên ở đâu?~Nhắn chatbot có biết chắc tài khoản tôi còn VIP không?~Tôi muốn kiểm tra gói đang dùng trước khi mua phim thì mở đâu?|Mở Tài khoản → Gói Đăng Ký để kiểm tra gói và thời hạn. Chatbot chỉ được xác nhận thông tin cá nhân khi phiên có dữ liệu hợp lệ; đáp án chung không đoán ngày hết hạn hoặc gói của bạn.
Tôi muốn biết phim MFILM có đủ tập hay chưa thì kiểm tra gì?~Nhãn số tập có nói chắc series ngoài đời đã kết thúc không?~Phim đang cập nhật có nên đoán tổng tập cuối cùng không?~Tôi muốn kiểm tra các tập đang phát được thay vì tổng dự kiến thì làm sao?|Mở Tập phim để xem các nguồn thực tế và đọc trạng thái ở trang chi tiết. Số mục đang có, nhãn tập gộp và tổng dự kiến là các khái niệm khác nhau. Nếu dữ liệu chưa rõ, chatbot không nên khẳng định phim đã hoàn tất.
Tôi có thể yêu cầu MFILM thêm phim chưa có trong kho không?~Tìm mãi không thấy phim muốn xem thì báo web ở đâu?~Muốn đề xuất một phim cho MFILM cần gửi gì?~Chatbot có tự nhập ngay phim tôi yêu cầu không?|Bạn có thể gửi tên, tên gốc, năm hoặc phần phim qua [Hỗ trợ](/ho-tro) để MFILM xem xét. Chatbot không cam kết tự nhập, có bản quyền phát hành hay thời điểm cập nhật nếu chưa có xác nhận.
Đánh giá phim và bình luận trên MFILM khác nhau thế nào?~Tôi muốn nêu cảm nhận mà không spoil cho người khác thì làm gì?~Muốn xem đánh giá của phim trên web vào đâu?~Chatbot có tự tạo điểm đánh giá của một phim không?|Xem phần Đánh giá và bình luận trên trang phim để đọc phản hồi đang có. Nếu viết nhận xét có tiết lộ nội dung, báo rõ spoil. Chatbot không tự tạo số sao hoặc số lượt đánh giá khi không có dữ liệu thực tế.
Gói của tôi đủ cấp nhưng video không chạy thì có nên mua lại không?~Phim không phát dù quyền xem hợp lệ có phải hết gói không?~Trả thêm tiền có sửa được server bị lỗi không?~Có quyền xem nhưng video quay vòng thì kiểm tra bước nào?|Kiểm tra gói hoặc thuê còn hạn, rồi thử server, tập và mạng. Lỗi nguồn phát không được xử lý bằng cách tự thanh toán lại. Nếu quyền hợp lệ mà vẫn không phát, gửi tên phim, tập và server qua Hỗ trợ.
Tôi tìm trên Google không thấy phim MFILM có phải web đã xóa phim không?~Phim có trên web nhưng chưa có kết quả tìm kiếm thì sao?~Bing chưa hiện tên phim thì tôi có tìm trong MFILM được không?~Muốn tìm phim trên web khi công cụ tìm kiếm chưa cập nhật nên vào đâu?|Dùng ô tìm kiếm của MFILM hoặc [Phim mới](/film-new) để đối chiếu kho hiện tại. Công cụ tìm kiếm có thời gian thu thập riêng; chưa có kết quả trên Google hoặc Bing không đủ để kết luận phim bị xóa khỏi web.
Tôi muốn lưu link MFILM để mở nhanh lần sau thì làm gì?~Bookmark trang phim có tự lưu tiến độ không?~Thêm web vào màn hình chính có tự mua gói không?~Lưu đường dẫn phim khác nút Yêu thích thế nào?|Bạn có thể đánh dấu trang trong trình duyệt hoặc thêm MFILM vào màn hình chính. Bookmark chỉ lưu liên kết; Yêu Thích lưu theo tài khoản và Xem Tiếp lưu tiến độ. Các thao tác lưu không tự mua gói hay thuê phim.
Tôi thấy phim đã thuê ở Phim Đang Thuê nhưng mở video không được thì sao?~Giao dịch thuê còn hạn mà một tập lỗi có phải đã hết quyền không?~Muốn hỗ trợ kiểm tra tập của phim đã thanh toán cần gửi gì?~Tôi thuê đúng phim mà server chết thì xử lý ra sao?|Kiểm tra ngày hết hạn và đúng tài khoản, rồi thử server hoặc bản chiếu khác của cùng tập. Nếu vẫn lỗi, gửi tên phim, tập, server và mã giao dịch qua Hỗ trợ để kiểm tra riêng nguồn và quyền xem.
Chatbot có phải gọi dịch vụ AI ngoài cho mọi câu MFILM không?~Các hướng dẫn web có thể trả lời ngay bằng kiến thức sẵn không?~Tôi hỏi thao tác thuê phim thì AI có cần đoán lại từ đầu không?~Câu hướng dẫn MFILM lặp lại được trả lời thế nào?|Hướng dẫn ổn định của MFILM ưu tiên bộ hỏi đáp sẵn. Tên phim, số tập, giá và quyền cá nhân cần dữ liệu hiện tại; câu chưa xử lý được mới dùng mô hình hỗ trợ. Đây là truy xuất đáp án, không phải cam kết AI biết mọi thứ.
Thông tin tài khoản của tôi có được dùng trả lời cho người khác không?~Bộ nhớ chung AI có nên lưu số giao dịch của tôi không?~Tôi hỏi tiến độ cá nhân có đưa vào kiến thức MFILM chung không?~Hỏi một đáp án dùng chung khác câu hỏi riêng về tài khoản thế nào?|Hướng dẫn chung có thể tái sử dụng, còn mật khẩu, thông tin tài khoản, mã giao dịch và ngữ cảnh riêng không được biến thành đáp án chung. Thông tin biến động cũng cần đối chiếu lại thay vì lưu như một sự thật cố định.
Tôi thấy đáp án AI về thuê không còn đúng thì báo ở đâu?~Muốn MFILM sửa câu hướng dẫn chatbot bị cũ phải làm gì?~Chatbot báo thời hạn khác 30 ngày thì tôi tin dữ liệu nào?~Một câu trả lời chung sai có nên được học tiếp không?|Đối chiếu chính sách và giao dịch đang áp dụng trên web. Phim thuê hiện có thời hạn 30 ngày kể từ thanh toán thành công. Gửi câu hỏi và đáp án sai qua Hỗ trợ để kiểm tra; đáp án sai không nên tiếp tục được dùng như kiến thức đã xác nhận.
Tôi cần chọn đúng bản chiếu trước khi báo thiếu tập thế nào?~Server khác nhau có thể có danh sách tập khác nhau không?~Một bản Vietsub đủ tập hơn thuyết minh có bất thường không?~Bản chiếu đang chọn không có tập cuối thì thử gì?|Kiểm tra từng bản chiếu và nguồn tương ứng trên phim. Các nguồn có thể cập nhật khác nhau hoặc gộp tập khác cách đánh số. Nếu vẫn thiếu, báo tên phim, bản chiếu và số tập; không mặc định mọi nguồn phải giống hệt nhau.
Tôi muốn bấm xem phim khi chưa đăng nhập MFILM thì sao?~Có cần đăng nhập để lưu yêu thích trên MFILM không?~Xem như khách có đồng bộ với tài khoản ở máy khác không?~Khi nào cần đăng nhập tài khoản để dùng web đầy đủ?|Bạn có thể duyệt thông tin phim công khai; các thao tác tài khoản như Yêu Thích, Danh Sách, thuê và đồng bộ cần đúng phiên đăng nhập. Tiến độ khách chỉ có phạm vi trình duyệt, không tự trở thành lịch sử chung trên mọi thiết bị.
Quên mật khẩu email Google có hỏi MFILM AI lấy lại được không?~AI có cung cấp lại mật khẩu cũ của tôi không?~Muốn khôi phục đăng nhập đúng tài khoản phải bắt đầu ở đâu?~Không đăng nhập được để xem phim thuê thì xin hỗ trợ thế nào?|Nếu dùng Google, khôi phục tài khoản qua Google rồi đăng nhập MFILM lại. Với email/mật khẩu MFILM, dùng hướng dẫn khôi phục đang có hoặc liên hệ Hỗ trợ để xác minh. Chatbot không đọc lại hay tiết lộ mật khẩu cũ.
Tôi muốn tìm nội dung phù hợp thay vì hỏi kiến thức ngẫu nhiên thì nhắn sao?~AI MFILM có ưu tiên hướng dẫn web và kho phim không?~Chatbot của website phim nên giúp tôi những việc nào?~Tôi hỏi chọn phim thì có cần chuyển sang câu hỏi học thuật không?|Trợ lý MFILM tập trung tìm phim trong kho, gợi ý theo nhu cầu và hướng dẫn dùng web: tập phim, server, xem tiếp, gói, thuê và tài khoản. Bạn cứ nêu việc muốn làm trên MFILM; không cần đổi sang câu hỏi học thuật.
`.trim();

const topics = rows.split('\n').map((row, index) => {
    const [questions, answer] = row.split('|');
    if (!questions || !answer) throw new Error(`Incomplete FAQ row ${index}`);
    return { id: `website-guide-${index + 1}`, questions: questions.split('~'), answer, tags: ['Hướng dẫn sử dụng MFILM'], scope: 'website' };
});
const { catalog } = JSON.parse(await readFile(new URL('../server/seo/catalog.json', import.meta.url), 'utf8'));
const { catalog: prepared } = prepareCatalog(catalog);
const movies = [...prepared.Movies].filter(movie => movie.otherName || movie.name).sort((a, b) => (Number(b.views) || 0) - (Number(a.views) || 0) || a.publicPath.localeCompare(b.publicPath)).slice(0, 200);
for (const movie of movies) {
    const title = movie.otherName || movie.name;
    const link = `[${title}](${movie.publicPath})`;
    const cases = [
        [`Muốn chọn một tập khác của ${title} trên MFILM thì bấm ở đâu?`, `Mở ${link} và chọn tab **Tập phim**. Dùng **Khoảng tập** để tới nhóm cần tìm rồi chọn video có nguồn. Mỗi nhóm chứa tối đa 120 mục; nhãn có thể nhảy số hoặc gộp nhiều tập, nên không tạo thêm tập chỉ từ số cuối.`],
        [`Tôi muốn lưu ${title} vào Yêu Thích trên MFILM thì làm sao?`, `Đăng nhập rồi mở ${link}, bấm **Yêu thích**. Tìm lại trong Tài khoản → Yêu Thích; bấm lại để bỏ lưu. Thao tác này lưu phim vào danh sách của bạn, không tự cấp quyền xem nếu phim yêu cầu gói hoặc thuê.`],
        [`Muốn thuê riêng ${title} thay vì mua cả gói MFILM thì kiểm tra ở đâu?`, `Mở ${link} để kiểm tra nhãn gói, quyền xem và lựa chọn thuê đang áp dụng. **Phim Free không cần trả giá thuê**; phim trả phí chỉ thuê khi có giá hợp lệ. Giao dịch thuê thành công cấp quyền phim đó trong **30 ngày**, không mở mọi phim trong gói. Mình không dùng đáp án sẵn để đoán giá hiện tại.`],
        [`Nếu ${title} không phát được trên MFILM thì tôi báo lỗi thế nào?`, `Kiểm tra đúng phim tại ${link}, chọn lại tập và thử server khác nếu có. Nếu vẫn lỗi, gửi tên **${title}**, số tập, bản chiếu, server và thời điểm lỗi qua [Hỗ trợ MFILM](/ho-tro). Không cần gửi mật khẩu hoặc thông tin thẻ.`],
        [`Tôi muốn gửi link ${title} trên MFILM cho bạn bè thì gửi trang nào?`, `Gửi trang chi tiết ${link}, hoặc mở trang đó và dùng **Chia sẻ**. Người nhận có thể xem thông tin và tự chọn tập; quyền gói hoặc quyền thuê của bạn không đi theo liên kết, nên mỗi tài khoản vẫn được kiểm tra quyền riêng.`],
    ];
    cases.forEach(([question, answer], index) => topics.push({ id: `website-film-${movie.routeSlug}-${index + 1}`, questions: [question], answer, tags: ['Tình huống theo phim trong kho MFILM'], scope: 'film-guide', publicPath: movie.publicPath }));
}
await writeFile(new URL('../src/ai/websiteKnowledge.json', import.meta.url), JSON.stringify(topics, null, 2) + '\n');
console.log(`Website batch: ${topics.length} topics, ${topics.reduce((sum, entry) => sum + entry.questions.length, 0)} distinct questions; ${movies.length} actual catalog movies. No current price, entitlement or release schedule is cached.`);
